#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
define('__ROOT__', __DIR__);

require(__ROOT__ . '/vendor/autoload.php');
require(__ROOT__ . '/vendor/yiisoft/yii2/Yii.php');
require(__ROOT__ . '/src/common/config/bootstrap.php');


$config = yii\helpers\ArrayHelper::merge(
    require(__ROOT__ . '/src/common/config/main.php'),
    require(__ROOT__ . '/src/common/config/local.php'),
    require(__ROOT__ . '/src/console/config/main.php'),
    require(__ROOT__ . '/src/console/config/local.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
